### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by AntoineTesson** [flrt/ght-opendata#1]
Bonjour,

Le lien https://solidarites-sante.gouv.fr/IMG/xlsx/dgos_ght_liste_2017_10_31.xlsx
Ne fonctionne plus, savez ou je peux trouver son équivalent ?

**Comment by flrt** [comment]
bonjour
En effet, l'URL a changé.
La nouvelle URL est : https://solidarites-sante.gouv.fr/IMG/xlsx/dgos_ght_liste_290119_2.xlsx
